// THIRD-PARTY-NOTICES.md: the licences of every package bundled into dist/index.js (what the npm package and the
// image ship), found from esbuild's metafile. `make notices` regenerates it; CI fails when it is out of date
// (scripts/notices.mjs --check). dist/sentry-sdk.js (image only) is listed in its own section.
import { build } from 'esbuild';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

async function bundled(entry) {
  const r = await build({
    entryPoints: [entry],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node22',
    write: false,
    metafile: true,
    logLevel: 'error',
    outfile: 'out.js',
    external: ['./sentry-sdk.js'],
  });
  const dirs = new Set();
  for (const input of Object.keys(r.metafile.inputs)) {
    const m = /^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//.exec(input);
    if (m) dirs.add(m[1]);
  }
  return [...dirs];
}

function info(dir) {
  const pkg = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8'));
  const file = readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.(md|txt))?$/i.test(f));
  const text = file ? readFileSync(path.join(dir, file), 'utf8').trim() : null;
  const license = typeof pkg.license === 'string' ? pkg.license : (pkg.license?.type ?? 'see the package');
  return { name: pkg.name, version: pkg.version, license, text, homepage: pkg.homepage ?? pkg.repository?.url ?? null };
}

function section(title, dirs) {
  const pkgs = [...new Map(dirs.map(info).map((p) => [`${p.name}@${p.version}`, p])).values()].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  const out = [`## ${title}`, '', ...pkgs.map((p) => `- ${p.name} ${p.version} (${p.license})`), ''];
  for (const p of pkgs) {
    out.push(`### ${p.name} ${p.version}`, '', `License: ${p.license}${p.homepage ? ` · ${p.homepage}` : ''}`, '');
    if (p.text) out.push('```text', p.text.replace(/```/g, "'''"), '```', '');
  }
  return out.join('\n');
}

const main = await bundled('src/index.ts');
const sentry = (await bundled('src/sentry-sdk.ts')).filter((d) => !main.includes(d));
const text = [
  '# Third-party notices',
  '',
  'The sol2flow MCP server (MIT, see LICENSE) bundles the following packages. Generated by `make notices`',
  '(scripts/notices.mjs); do not edit.',
  '',
  section('Bundled into dist/index.js (npm package and image)', main),
  section('Bundled into dist/sentry-sdk.js (image only)', sentry),
].join('\n');

if (process.argv.includes('--check')) {
  const current = existsSync('THIRD-PARTY-NOTICES.md') ? readFileSync('THIRD-PARTY-NOTICES.md', 'utf8') : '';
  if (current !== text) {
    console.error('THIRD-PARTY-NOTICES.md is out of date: run make notices');
    process.exit(1);
  }
} else {
  writeFileSync('THIRD-PARTY-NOTICES.md', text);
  console.error(`THIRD-PARTY-NOTICES.md: ${main.length} + ${sentry.length} packages`);
}
