// src/api/openapi.d.ts from the vendored OpenAPI snapshot (openapi/openapi-<version>.json): the response and request
// types the client and the formatters use. Run by `make openapi-sync`; the file is committed.
import { readdirSync, writeFileSync } from 'node:fs';
import openapiTS, { astToString } from 'openapi-typescript';

const files = readdirSync('openapi').filter((f) => /^openapi-\d+\.\d+\.\d+\.json$/.test(f));
if (files.length !== 1)
  throw new Error(`expected exactly one openapi/openapi-<version>.json, found: ${files.join(', ')}`);
const ast = await openapiTS(new URL(`../openapi/${files[0]}`, import.meta.url), { alphabetize: false });
const header = `// Generated by scripts/openapi-types.mjs from openapi/${files[0]} (make openapi-sync). Do not edit.\n\n`;
writeFileSync('src/api/openapi.d.ts', header + astToString(ast));
console.error(`src/api/openapi.d.ts ← openapi/${files[0]}`);
